name: First workflow

on: push

jobs: 
  build: 
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    
    steps: 
      - uses: actions/checkout@v3

      - name: Run a sample github action
        run: echo "This workflow run successfully for this particular github actions"
